### ISSUE TITLE
Category not showing in preferences menu

### ISSUE THREAD

**Issue by autumnwalker** [SillyGoat/PIAPortForward#1]
Using Deluge 1.3.12 (daemon, linux) with WebUI.

Able to get the .egg file into Deluge and activated via WebGUI, but the category does not display in the preferences menu.

**Comment by SillyGoat** [comment]
Implemented a WebGUI version.  Seems to work for me now.  Please try 1.1 to see if it works for you.  If it does, feel free to close this issue.

**Comment by autumnwalker** [comment]
Added the new egg file via WebUI and tried to enable, now getting the following error in deluged.log

`Unable to instantiate plugin!
__init__() takes exactly 1 argument (2 given)
File "/usr/lib/python2.7/dist-packages/deluge/pluginmanagerbase.py", line 144, in enable_plugin
    instance = cls(plugin_name.replace("-", "_"))
  File "/var/lib/deluge/.config/deluge/plugins/PIAPortForward-1.1-py2.7.egg/piaportforward/__init__.py", line 46, in __init__
    super(CorePlugin, self).__init__(plugin_name)
  File "/usr/lib/python2.7/dist-packages/deluge/plugins/init.py", line 44, in __init__
    self.plugin = self._plugin_cls(plugin_name)
TypeError: __init__() takes exactly 1 argument (2 given)`

**Comment by SillyGoat** [comment]
Sorry about that.  See if 1.1.1 works for you.

**Comment by autumnwalker** [comment]
I think we are getting closer. I get a 404 error now when trying to load the plugin (screenshot attached).

![error](https://cloud.githubusercontent.com/assets/11489678/21073851/0577672c-bec1-11e6-9e53-d472778d2f44.jpg)

**Comment by SillyGoat** [comment]
Unfortunately, I can't seem to reproduce this new issue locally. This seems like a client-side issue. To help me reproduce it, can you provide the following information?

Your web browser details
Console debug output from the browser

Browser console output would generate similar information to the deluged.log that you provided initially.

**Comment by autumnwalker** [comment]
I appreciate your help with this!

Browser is Chrome 54.0.2840.99 m (Windows 10). Console output is as follows:

`ext-base.js:7
GET http://<servername>:8112/js/piaportforward/piaportforward.js?_dc=1481410011470 404 (Not Found)
i @ ext-base.js:7
request @ ext-base.js:7
request @ ext-all.js:7
Ext.ux.JSLoader @ ext-extensions.js:63
(anonymous function) @ deluge-all.js:257
each @ ext-base.js:7
onGotPluginResources @ deluge-all.js:257
_onSuccess @ deluge-all.js:154
handleResponse @ ext-all.js:7
f @ ext-base.js:7m @ ext-base.js:7
(anonymous function) @ ext-base.js:7`

**Comment by SillyGoat** [comment]
Ok.  It seems like I can only reproduce the issue if I manually corrupt the deluge plugin folder on my NAS server.  Would it be possible for you to delete the plugin, it's cached location, then reinstall?

For me, the plugin is located in my user's (i.e. admin) config folder similar to...

.../.config/deluge/plugins/PIAPortForward-1.1.1-py2.7.egg

The plugin cached version is located in a .python-eggs folder similar to...

.../.python-eggs/PIAPortForward-1.1.1-py2.7.egg-tmp/*

The reason you're getting that error is because the deluge http server cannot find the following file...

.../.python-eggs/PIAPortForward-1.1.1-py2.7.egg-tmp/piaportforward/data/piaportforward.js

on your local NAS filesystem.  I ended up reproducing this when I renamed the JS file to something random and refreshed the webpage.  Unfortunately, Deluge controls most of how the plugin installation and updating works.  So there may be a bug in Deluge itself when it comes to updating plugins.

Perhaps you can verify this on your NAS?  I'm not sure what else to suggest other than delete/reinstall.

**Comment by autumnwalker** [comment]
Success! Thank you.

Now ... how can I tell if it has forwarded the correct port?

**Comment by SillyGoat** [comment]
The easiest way to tell is to use the native client for your operating system.  On the native client, there's a button called "Test Active Port" in the Network category.  After clicking it, if you see a green circle, it indicates that the port (and plugin) is working correctly.

Since you use the WebUI, you won't see this (I don't know why Deluge doesn't have this for the webui).

The 2nd way to tell is to see if your torrents can do any uploading while your PIA VPN connection is active.  If you can upload at any speed, it means that the port forwarding is active.  If you see zero bytes uploaded, it means there are no leechers or its not working.

The 3rd way to tell is to look at the deluged.log like the one you sent me earlier.  If it's successful, you will see something like this...

[INFO    ] 04:08:01 build\bdist.win-amd64\egg\piaportforward\core:104 Slow port refresh
[INFO    ] 04:08:01 build\bdist.win-amd64\egg\piaportforward\core:118 Refreshing listening port...
[INFO    ] 04:08:01 build\bdist.win-amd64\egg\piaportforward\core:126 Current listening port: 44666
[INFO    ] 04:08:02 build\bdist.win-amd64\egg\piaportforward\core:131 port is open

Slow port refresh attempts a refresh every hour and only happens when the port is open and active.  It's "slow" because I didn't want to keep hammering the VPN server every second requesting for ports.

BTW, a "fast" port refresh attempts a refresh every 5 seconds while the port is closed.  It will keep requesting like this until a port is opened.  To tell if the forwarding port is open, I make use of deluge's "test active port" feature provided by their API (same as the button mentioned earlier).

**Comment by autumnwalker** [comment]
Thank you so much!
